# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_14(object):
    def setupUi(self, Form_14):
        Form_14.setObjectName("Form_14")
        Form_14.resize(961, 1028)
        self.label_1 = QtWidgets.QLabel(Form_14)
        self.label_1.setGeometry(QtCore.QRect(-250, 0, 851, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form_14)
        self.label_2.setGeometry(QtCore.QRect(540, 130, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_14)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_14)
        self.label_4.setGeometry(QtCore.QRect(560, 540, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_14)
        self.label_5.setGeometry(QtCore.QRect(40, 540, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_5.setObjectName("label_5")
        self.tableWidget_13 = QtWidgets.QTableWidget(Form_14)
        self.tableWidget_13.setGeometry(QtCore.QRect(510, 200, 411, 321))
        self.tableWidget_13.setRowCount(8)
        self.tableWidget_13.setColumnCount(7)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_14 = QtWidgets.QTableWidget(Form_14)
        self.tableWidget_14.setGeometry(QtCore.QRect(20, 200, 411, 321))
        self.tableWidget_14.setRowCount(8)
        self.tableWidget_14.setColumnCount(7)
        self.tableWidget_14.setObjectName("tableWidget_14")
        self.tableWidget_15 = QtWidgets.QTableWidget(Form_14)
        self.tableWidget_15.setGeometry(QtCore.QRect(500, 620, 451, 321))
        self.tableWidget_15.setRowCount(8)
        self.tableWidget_15.setColumnCount(7)
        self.tableWidget_15.setObjectName("tableWidget_15")
        self.tableWidget_16 = QtWidgets.QTableWidget(Form_14)
        self.tableWidget_16.setGeometry(QtCore.QRect(20, 620, 411, 321))
        self.tableWidget_16.setRowCount(8)
        self.tableWidget_16.setColumnCount(7)
        self.tableWidget_16.setObjectName("tableWidget_16")
        self.pushButton_44 = QtWidgets.QPushButton(Form_14)
        self.pushButton_44.setGeometry(QtCore.QRect(740, 530, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(Form_14)
        self.pushButton_45.setGeometry(QtCore.QRect(250, 540, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_47 = QtWidgets.QPushButton(Form_14)
        self.pushButton_47.setGeometry(QtCore.QRect(250, 950, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_46 = QtWidgets.QPushButton(Form_14)
        self.pushButton_46.setGeometry(QtCore.QRect(770, 950, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")

        self.retranslateUi(Form_14)
        QtCore.QMetaObject.connectSlotsByName(Form_14)

    def retranslateUi(self, Form_14):
        _translate = QtCore.QCoreApplication.translate
        Form_14.setWindowTitle(_translate("Form_14", "Form"))
        self.label_1.setText(_translate("Form_14", "عرض النتائج"))
        self.label_2.setText(_translate("Form_14", "CS"))
        self.label_3.setText(_translate("Form_14", "SE"))
        self.label_4.setText(_translate("Form_14", "IT"))
        self.label_5.setText(_translate("Form_14", "IS"))
        self.pushButton_44.setText(_translate("Form_14", "عرض "))
        self.pushButton_45.setText(_translate("Form_14", "عرض "))
        self.pushButton_47.setText(_translate("Form_14", "عرض "))
        self.pushButton_46.setText(_translate("Form_14", "عرض "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_14 = QtWidgets.QWidget()
    ui = Ui_Form_14()
    ui.setupUi(Form_14)
    Form_14.show()
    sys.exit(app.exec_())
